# Generated by Django 3.2.7 on 2021-09-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pincode',
            name='place',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
